# Generated by Django 2.0.6 on 2018-08-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180828_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Warehouse_Mapping',
            new_name='ItemWarehouseMapping',
        ),
    ]
