# Generated by Django 2.0.6 on 2018-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180830_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritemmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='voucheritemmapping',
            name='item',
        ),
        migrations.AddField(
            model_name='voucheritemmapping',
            name='item',
            field=models.ManyToManyField(to='inventory.Item'),
        ),
    ]
