# Generated by Django 2.0.6 on 2018-09-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180901_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritemmapping',
            name='item',
        ),
        migrations.AddField(
            model_name='voucheritemmapping',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
