# Generated by Django 2.0.6 on 2018-09-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180901_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheritemmapping',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
